/** Template themes: palettes, naming vocab, part-tag affinities and which everyday-object groups fit. */
import type { ObjGroup } from '../gen/obj/objkit';

export type Palette = [main: string, accent: string, dark: string];

export interface Theme {
  id: string;
  label: string;
  /** name adjectives ("Clockwork", "Brass" ...) */
  adj: string[];
  /** "X of <epithet>" for melee names */
  epithets: string[];
  palettes: Palette[];
  /** part tags that fit this theme (weight boost) */
  like: string[];
  /** part tags that clash (weight penalty) */
  avoid: string[];
  /** everyday object groups that naturally belong (home groups) */
  groups: ObjGroup[];
  /** other object groups allowed at lower weight; 'any' = all groups */
  alsoGroups: ObjGroup[] | 'any';
  /** deco id substrings preferred */
  decoWords: string[];
  /** search keywords */
  keywords: string[];
  /** class noun overrides ("Blunderbuss" for pirate shotguns ...) */
  nouns?: Partial<Record<string, string[]>>;
  /** tint for metal melee blades (undefined = keep steel) */
  blade?: 'steel' | 'palette' | 'glow';
}

const ALL_GROUPS: ObjGroup[] = ['kitchen', 'household', 'garden', 'sports', 'music', 'office', 'toy', 'food', 'weapon'];

export const THEMES: Theme[] = [
  {
    id: 'military',
    label: 'Military',
    adj: ['Tactical', 'Combat', 'Field', 'Recon', 'Spec-Ops', 'Service', 'Strike', 'Ranger', 'Patrol', 'Delta'],
    epithets: ['the Sergeant', 'Last Resort', 'the Front Line', 'Shock and Awe'],
    palettes: [
      ['#4b5320', '#c8a24a', '#2b2d24'],
      ['#3a3d33', '#25272b', '#1d1f23'],
      ['#5c5446', '#2b2b2b', '#1f1f22'],
      ['#2f3238', '#ff7a1a', '#1d1f23'],
      ['#6b6b4a', '#3b3b2a', '#222219'],
    ],
    like: ['military', 'tactical', 'modern', 'boxy', 'compact', 'heavy', 'precision', 'stealth'],
    avoid: ['toy', 'silly', 'organic', 'alien', 'cute', 'magic', 'festive'],
    groups: ['weapon'],
    alsoGroups: ['garden', 'household', 'sports', 'kitchen', 'office'],
    decoWords: ['bandana', 'tally', 'name-tag', 'rivet', 'antenna', 'chain', 'sticker-number', 'sticker-warning', 'skull', 'led'],
    keywords: ['military', 'army', 'tactical', 'soldier', 'combat', 'modern', 'camo', 'special forces', 'marine'],
  },
  {
    id: 'scifi',
    label: 'Sci-Fi',
    adj: ['Plasma', 'Quantum', 'Photon', 'Ion', 'Laser', 'Fusion', 'Nova', 'Graviton', 'Star', 'Neutrino', 'Hyper'],
    epithets: ['the Void', 'Tomorrow', 'the Stars', 'Andromeda'],
    palettes: [
      ['#e8ebf0', '#19d3ff', '#2b2f38'],
      ['#20232b', '#7cff4f', '#2b2f38'],
      ['#1b1d2a', '#ff2bd6', '#24263a'],
      ['#c8ccd4', '#ffb000', '#3a3f4a'],
      ['#2a2440', '#8a5cff', '#15121f'],
    ],
    like: ['scifi', 'sleek', 'energy', 'tech', 'modern', 'glow', 'futuristic'],
    avoid: ['wood', 'medieval', 'ancient', 'tribal', 'steampunk', 'western'],
    groups: ['weapon'],
    alsoGroups: 'any',
    decoWords: ['led', 'antenna', 'dish', 'tesla', 'solar', 'lightbulb', 'halo', 'cube'],
    keywords: ['scifi', 'sci-fi', 'space', 'laser', 'plasma', 'future', 'futuristic', 'alien tech', 'energy', 'ray'],
    nouns: { pistol: ['Blaster', 'Ray Gun', 'Phaser'], rifle: ['Pulse Rifle', 'Rifle', 'Carbine'], smg: ['Ion SMG', 'Burst Blaster'], sniper: ['Railgun', 'Lance'], melee: ['Saber'] },
    blade: 'glow',
  },
  {
    id: 'steampunk',
    label: 'Steampunk',
    adj: ['Steampunk', 'Clockwork', 'Brass', 'Victorian', 'Cogwork', 'Aether', 'Gaslamp', 'Boiler'],
    epithets: ['the Inventor', 'Gears', 'the Aether', 'Lord Brassington'],
    palettes: [
      ['#7a4a28', '#c99a2e', '#3a2a1a'],
      ['#5a3820', '#d4a843', '#2b1d12'],
      ['#4a2e18', '#b87333', '#2a1a0e'],
      ['#8b6b3d', '#c0c0c0', '#3b2b1b'],
    ],
    like: ['steampunk', 'ornate', 'brass', 'wood', 'retro', 'clockwork'],
    avoid: ['scifi', 'modern', 'plastic', 'tactical', 'energy'],
    groups: [],
    alsoGroups: 'any',
    decoWords: ['gear', 'pipes', 'rivet', 'top-hat', 'tesla', 'lightbulb', 'bell', 'chain'],
    keywords: ['steampunk', 'clockwork', 'brass', 'victorian', 'gears', 'steam', 'cog', 'inventor'],
    nouns: { shotgun: ['Blunderbuss', 'Scattergun'], pistol: ['Pepperbox', 'Pistol'], rifle: ['Long Rifle', 'Repeater'], flamethrower: ['Steam Torch', 'Boiler Cannon'] },
  },
  {
    id: 'medieval',
    label: 'Medieval',
    adj: ['Knightly', 'Iron', 'Crusader', 'Castle', 'Feudal', 'Squire', 'Templar', 'Siege'],
    epithets: ['the Realm', 'the Crusade', 'Camelot', 'the Black Knight', 'the Round Table'],
    palettes: [
      ['#a7adb6', '#6e4424', '#3a2a1a'],
      ['#8e959e', '#c99a2e', '#4a3520'],
      ['#9aa1ab', '#7a1f1f', '#2b2b2b'],
      ['#b0b5bc', '#2a4a8a', '#3a3a40'],
    ],
    like: ['medieval', 'wood', 'ornate', 'fantasy', 'viking', 'heavy', 'brutal', 'classic', 'ancient'],
    avoid: ['scifi', 'modern', 'tech', 'plastic', 'tactical', 'energy', 'toy'],
    groups: ['weapon'],
    alsoGroups: ['garden', 'kitchen', 'music'],
    decoWords: ['flag', 'banner', 'crown', 'chain', 'feather', 'skull', 'candle', 'tassel'],
    keywords: ['medieval', 'knight', 'castle', 'king', 'sword', 'crusade', 'dark ages', 'fantasy'],
    nouns: { crossbow: ['Crossbow', 'Arbalest'], grenade_launcher: ['Trebuchet', 'Mangonel'], rocket_launcher: ['Siege Cannon', 'Ballista'] },
  },
  {
    id: 'toy',
    label: 'Toy',
    adj: ['Toy', 'Squeaky', 'Foam', 'Bouncy', 'Plastic', 'Junior', 'Super', 'Mega'],
    epithets: ['Playtime', 'the Toybox', 'Recess', 'Bedtime'],
    palettes: [
      ['#ff7a30', '#2ec4f1', '#ffd23f'],
      ['#3bc9db', '#ff4f9a', '#ffd23f'],
      ['#7bd389', '#ffd23f', '#ff5e5b'],
      ['#a06cd5', '#ffd23f', '#3bc9db'],
      ['#ff5e5b', '#ffffff', '#2ec4f1'],
    ],
    like: ['toy', 'silly', 'chunky', 'plastic', 'cute'],
    avoid: ['brutal', 'military', 'tactical', 'spooky'],
    groups: ['toy'],
    alsoGroups: 'any',
    decoWords: ['googly', 'propeller', 'duck', 'pompom', 'sticker', 'bike-horn', 'party', 'unicorn', 'plushie'],
    keywords: ['toy', 'kids', 'foam', 'plastic', 'nerf', 'playtime', 'fun', 'squeaky'],
    blade: 'palette',
  },
  {
    id: 'kitchen',
    label: 'Kitchen',
    adj: ['Kitchen', "Chef's", 'Cast-Iron', 'Sizzling', 'Gourmet', 'Diner', 'Bistro', 'Grandma\'s Kitchen'],
    epithets: ['the Head Chef', 'Hell\'s Kitchen', 'the Sunday Roast', 'Fine Dining'],
    palettes: [
      ['#2b2b2e', '#c0c4ca', '#5a3a22'],
      ['#e8e4dc', '#d62828', '#3a3a3a'],
      ['#c0c4ca', '#2b2b2e', '#7a4a28'],
      ['#f2efe8', '#3bb273', '#2b2b2b'],
      ['#b87333', '#2b2b2b', '#5a3820'],
    ],
    like: ['kitchen', 'food', 'metal', 'silly', 'improvised'],
    avoid: ['military', 'tactical', 'scifi'],
    groups: ['kitchen', 'food'],
    alsoGroups: ['household'],
    decoWords: ['coffee', 'donut', 'pizza', 'chili', 'carrot', 'banana', 'cherry', 'candle'],
    keywords: ['kitchen', 'cooking', 'chef', 'cook', 'cookware', 'utensil', 'restaurant', 'diner'],
  },
  {
    id: 'garden',
    label: 'Garden',
    adj: ['Garden', 'Backyard', 'Green-Thumb', 'Allotment', 'Lawn', 'Greenhouse', 'Hedge', 'Compost'],
    epithets: ['the Groundskeeper', 'the Allotment', 'Weeds', 'the Hedge'],
    palettes: [
      ['#3a7d2c', '#ffb000', '#2b2b2b'],
      ['#2f6b3a', '#c0392b', '#4a3520'],
      ['#5a8f29', '#8a5a32', '#2b2b2b'],
      ['#ff7a1a', '#2b2b2b', '#3a3a3a'],
      ['#d4c82e', '#2b2b2b', '#3a7d2c'],
    ],
    like: ['garden', 'farm', 'tools', 'wood', 'organic', 'industrial', 'power-tool'],
    avoid: ['scifi', 'tactical', 'royal'],
    groups: ['garden'],
    alsoGroups: ['food', 'household'],
    decoWords: ['flower', 'cactus', 'mushroom', 'carrot', 'chili', 'feather'],
    keywords: ['garden', 'gardening', 'yard', 'lawn', 'tool', 'tools', 'farm', 'shed', 'diy', 'hardware'],
  },
  {
    id: 'office',
    label: 'Office',
    adj: ['Office', 'Corporate', 'Cubicle', 'Executive', 'Middle-Management', 'Overtime', 'Quarterly', 'HR-Approved'],
    epithets: ['the Quarterly Review', 'Monday Morning', 'the Board Meeting', 'Synergy'],
    palettes: [
      ['#c8ccd4', '#2a5bd7', '#2b2b2b'],
      ['#2b2b2e', '#d4d7dc', '#1d1f23'],
      ['#f2efe8', '#ffb000', '#3a3a3a'],
      ['#3b4a5a', '#e04a3a', '#20262e'],
    ],
    like: ['office', 'school', 'tech', 'modern', 'plastic', 'compact'],
    avoid: ['medieval', 'tribal', 'organic'],
    groups: ['office', 'household'],
    alsoGroups: [],
    decoWords: ['coffee', 'name-tag', 'sticker', 'lightbulb', 'keychain'],
    keywords: ['office', 'work', 'desk', 'school', 'stationery', 'corporate', 'business', 'cubicle'],
  },
  {
    id: 'sports',
    label: 'Sports',
    adj: ['Pro', 'Varsity', 'Championship', 'All-Star', 'Stadium', 'MVP', 'Grand-Slam', 'Locker-Room'],
    epithets: ['the Champion', 'the Big Game', 'Overtime', 'the Final Whistle'],
    palettes: [
      ['#f2efe8', '#d62828', '#1f3a8a'],
      ['#1f3a8a', '#ffd23f', '#f2efe8'],
      ['#2b2b2b', '#3bb273', '#f2efe8'],
      ['#ff7a1a', '#2b2b2b', '#f2efe8'],
      ['#8a5a32', '#f2efe8', '#2b2b2b'],
    ],
    like: ['sports', 'sport', 'rubber', 'plastic', 'modern'],
    avoid: ['medieval', 'spooky', 'tribal'],
    groups: ['sports'],
    alsoGroups: [],
    decoWords: ['sticker-number', 'sticker-stripes', 'pompom', 'tassel', 'name-tag', 'bike-horn'],
    keywords: ['sports', 'sport', 'athlete', 'game', 'ball', 'team', 'stadium', 'gym'],
  },
  {
    id: 'music',
    label: 'Music',
    adj: ['Rock', 'Jazz', 'Punk', 'Heavy-Metal', 'Disco', 'Symphonic', 'Funky', 'Encore'],
    epithets: ['Rock and Roll', 'the Encore', 'the Final Chord', 'the Mosh Pit'],
    palettes: [
      ['#1b1b1b', '#c99a2e', '#f2efe8'],
      ['#c0392b', '#f2efe8', '#2b2b2b'],
      ['#8a5a32', '#e8c07a', '#2b2b2b'],
      ['#2a2440', '#ff2bd6', '#19d3ff'],
      ['#d4a843', '#2b2b2b', '#7a4a28'],
    ],
    like: ['music', 'musical', 'brass', 'wood', 'retro', 'rock', 'jazz'],
    avoid: ['tactical', 'military'],
    groups: ['music'],
    alsoGroups: [],
    decoWords: ['sticker-lightning', 'sticker-star', 'flame', 'spikes', 'led', 'bell', 'skull'],
    keywords: ['music', 'musical', 'instrument', 'rock', 'band', 'concert', 'song', 'sound', 'sonic', 'loud'],
    nouns: { shotgun: ['Boom Box', 'Shotgun'], lmg: ['Riff Cannon', 'Machine Gun'] },
  },
  {
    id: 'food',
    label: 'Food',
    adj: ['Tasty', 'Crispy', 'Juicy', 'Spicy', 'Sweet', 'Fresh', 'Snack', 'Deluxe'],
    epithets: ['the Buffet', 'Second Helpings', 'the Food Fight', 'Lunchtime'],
    palettes: [
      ['#d99b4a', '#f3d79a', '#7a4a28'],
      ['#ffd23f', '#d62828', '#3a7d2c'],
      ['#ff9ec4', '#7a4a28', '#f2efe8'],
      ['#3a7d2c', '#ff7a1a', '#5a3820'],
      ['#f2efe8', '#ff4f9a', '#7a4a28'],
    ],
    like: ['food', 'fruit', 'vegetable', 'sweet', 'dessert', 'organic', 'silly', 'french'],
    avoid: ['military', 'tactical'],
    groups: ['food'],
    alsoGroups: ['kitchen'],
    decoWords: ['donut', 'pizza', 'chili', 'carrot', 'banana', 'cherry', 'coffee', 'mushroom'],
    keywords: ['food', 'snack', 'edible', 'tasty', 'meal', 'lunch', 'fruit', 'veggie', 'food fight'],
  },
  {
    id: 'party',
    label: 'Party',
    adj: ['Party', 'Birthday', 'Confetti', 'Fiesta', 'Disco', 'Surprise', 'Glitter', 'Celebration'],
    epithets: ['the Party', 'Surprise', 'the After-Party', 'Many Happy Returns'],
    palettes: [
      ['#ff4f9a', '#ffd23f', '#2ec4f1'],
      ['#a06cd5', '#7bd389', '#ffd23f'],
      ['#2ec4f1', '#ff5e5b', '#ffffff'],
      ['#ffd23f', '#ff4f9a', '#a06cd5'],
    ],
    like: ['party', 'toy', 'silly', 'birthday', 'cute', 'festive', 'holiday'],
    avoid: ['brutal', 'military', 'spooky'],
    groups: ['toy'],
    alsoGroups: ['food', 'music'],
    decoWords: ['party', 'bow', 'candle', 'pompom', 'balloon', 'propeller', 'cherry', 'donut', 'sticker-star'],
    keywords: ['party', 'birthday', 'celebration', 'confetti', 'balloon', 'fiesta', 'festive', 'surprise'],
    blade: 'palette',
  },
  {
    id: 'alien',
    label: 'Alien',
    adj: ['Alien', 'Xeno', 'Bio', 'Mutant', 'Hive', 'Spore', 'Gooey', 'Martian'],
    epithets: ['the Hive', 'Planet X', 'the Swarm', 'Zeta Reticuli'],
    palettes: [
      ['#6b3fa0', '#b6ff3b', '#2a1a3a'],
      ['#2f6b3a', '#ff2bd6', '#1a2a1a'],
      ['#3ad6a0', '#ff5e00', '#1a3a30'],
      ['#8a2a4a', '#ffd23f', '#2a0a1a'],
    ],
    like: ['organic', 'alien', 'weird', 'scifi', 'glow', 'energy'],
    avoid: ['military', 'wood', 'classic', 'medieval'],
    groups: [],
    alsoGroups: 'any',
    decoWords: ['tentacle', 'eyeball', 'antenna', 'spikes', 'mushroom', 'fin'],
    keywords: ['alien', 'organic', 'bio', 'xeno', 'mutant', 'slime', 'goo', 'ufo', 'martian', 'creature'],
    blade: 'glow',
  },
  {
    id: 'pirate',
    label: 'Pirate',
    adj: ['Pirate', 'Buccaneer', 'Corsair', 'Seadog', 'Jolly Roger', "Captain's", 'Cutthroat', 'Davy Jones\''],
    epithets: ['the Seven Seas', 'Davy Jones', 'the Black Pearl', 'Plunder', 'the Plank'],
    palettes: [
      ['#4a2e18', '#c99a2e', '#2b2b2b'],
      ['#2b2b2b', '#c0392b', '#c99a2e'],
      ['#6e4424', '#e8e2d0', '#1b1b1b'],
      ['#3a2a1a', '#d4a843', '#7a1f1f'],
    ],
    like: ['pirate', 'wood', 'ornate', 'retro', 'brass', 'nautical', 'steampunk', 'classic'],
    avoid: ['scifi', 'tactical', 'modern', 'energy', 'plastic'],
    groups: ['weapon'],
    alsoGroups: ['food', 'kitchen', 'music'],
    decoWords: ['skull', 'flag', 'feather', 'chain', 'fish', 'bandana', 'tally', 'parrot'],
    keywords: ['pirate', 'buccaneer', 'sea', 'ship', 'captain', 'treasure', 'arr', 'corsair', 'nautical'],
    nouns: { shotgun: ['Blunderbuss'], pistol: ['Flintlock', 'Pistol'], rifle: ['Musket'], rocket_launcher: ['Deck Cannon'], grenade_launcher: ['Mortar'], melee: ['Cutlass'] },
  },
  {
    id: 'cowboy',
    label: 'Cowboy',
    adj: ['Frontier', 'Outlaw', 'Sheriff\'s', 'Dusty', 'Wild West', 'Rodeo', 'Gunslinger', 'Saloon'],
    epithets: ['the Frontier', 'High Noon', 'Tombstone', 'the Dusty Trail'],
    palettes: [
      ['#8a5a32', '#c0c0c0', '#3a2a1a'],
      ['#7d848e', '#c99a2e', '#5a3820'],
      ['#a0522d', '#f2efe8', '#2b2b2b'],
      ['#5c4033', '#d4a843', '#2b1d12'],
    ],
    like: ['western', 'cowboy', 'wood', 'retro', 'brass', 'revolver', 'classic'],
    avoid: ['scifi', 'tactical', 'energy', 'plastic', 'eastern'],
    groups: ['weapon'],
    alsoGroups: ['garden', 'music', 'kitchen'],
    decoWords: ['sticker-star', 'tally', 'feather', 'cactus', 'tassel', 'bandana', 'skull'],
    keywords: ['cowboy', 'western', 'wild west', 'outlaw', 'sheriff', 'frontier', 'gunslinger', 'saloon', 'ranch'],
    nouns: { pistol: ['Six-Shooter', 'Revolver', 'Peacemaker'], rifle: ['Lever Rifle', 'Repeater'], shotgun: ['Coach Gun', 'Scattergun'], melee: ['Bowie'] },
  },
  {
    id: 'ninja',
    label: 'Ninja',
    adj: ['Shadow', 'Ninja', 'Silent', 'Shinobi', 'Ronin', 'Midnight', 'Lotus', 'Samurai'],
    epithets: ['the Shadow Clan', 'the Silent Night', 'the Hidden Leaf', 'the Last Ronin'],
    palettes: [
      ['#1b1b1b', '#c0392b', '#2b2b2b'],
      ['#2b2b2e', '#e8e2d0', '#111111'],
      ['#1f2a3a', '#c99a2e', '#0f141c'],
      ['#3a1a1a', '#d8dce2', '#111111'],
    ],
    like: ['eastern', 'ninja', 'samurai', 'sleek', 'compact', 'light', 'stealth'],
    avoid: ['toy', 'silly', 'western', 'steampunk', 'heavy'],
    groups: ['weapon'],
    alsoGroups: ['kitchen', 'garden', 'music'],
    decoWords: ['tassel', 'bandana', 'chain', 'feather', 'sticker-lightning'],
    keywords: ['ninja', 'samurai', 'shinobi', 'stealth', 'japanese', 'eastern', 'martial arts', 'shadow', 'assassin'],
    nouns: { melee: ['Katana', 'Blade'], blowgun: ['Fukiya', 'Blowpipe'], crossbow: ['Repeater'] },
  },
  {
    id: 'junkyard',
    label: 'Junkyard',
    adj: ['Scrap', 'Junkyard', 'Rusty', 'Salvaged', 'Jury-Rigged', 'Wasteland', 'Duct-Tape', 'Makeshift'],
    epithets: ['the Wasteland', 'Spare Parts', 'the Scrap Heap', 'Last Week\'s Trash'],
    palettes: [
      ['#8a6a4a', '#b0602a', '#3a3a3a'],
      ['#6b6b5a', '#d4a843', '#2b2b2b'],
      ['#7a5a3a', '#5a8f9a', '#2b2b2b'],
      ['#5a5a5a', '#c0392b', '#3a2a1a'],
    ],
    like: ['junk', 'industrial', 'heavy', 'retro', 'tools', 'brutal', 'improvised', 'punk'],
    avoid: ['royal', 'fancy', 'sleek', 'clean'],
    groups: ['garden', 'household'],
    alsoGroups: 'any',
    decoWords: ['pipes', 'rivet', 'chain', 'spikes', 'tally', 'traffic-cone', 'sticker-warning', 'name-tag'],
    keywords: ['junk', 'junkyard', 'scrap', 'rusty', 'improvised', 'makeshift', 'wasteland', 'post-apocalyptic', 'duct tape', 'trash'],
  },
  {
    id: 'holiday',
    label: 'Holiday',
    adj: ['Festive', 'Jolly', 'Yuletide', 'Candy-Cane', 'Snowy', 'Merry', 'Gingerbread', 'Tinsel'],
    epithets: ['the North Pole', 'Christmas Morning', 'Good Cheer', 'the Naughty List'],
    palettes: [
      ['#c0392b', '#f2efe8', '#2f6b3a'],
      ['#2f6b3a', '#d4a843', '#c0392b'],
      ['#f2efe8', '#c0392b', '#2b5f6b'],
      ['#7a1f1f', '#e8e2d0', '#2f6b3a'],
    ],
    like: ['holiday', 'festive', 'party', 'silly', 'cute'],
    avoid: ['brutal', 'military', 'spooky'],
    groups: ['toy'],
    alsoGroups: 'any',
    decoWords: ['candle', 'bow', 'bell', 'party', 'cherry', 'pompom', 'sticker-star', 'halo'],
    keywords: ['holiday', 'christmas', 'xmas', 'festive', 'santa', 'winter', 'gift', 'present', 'easter', 'new year'],
    blade: 'palette',
  },
  {
    id: 'underwater',
    label: 'Underwater',
    adj: ['Deep-Sea', 'Coral', 'Abyssal', 'Tidal', 'Kraken', 'Diver\'s', 'Reef', 'Atlantean'],
    epithets: ['the Deep', 'Atlantis', 'the Kraken', 'the Mariana Trench'],
    palettes: [
      ['#2b5f6b', '#ffb000', '#1a3a40'],
      ['#3ad6c8', '#ff7a5a', '#1a4a5a'],
      ['#1f3a8a', '#c99a2e', '#0f1f4a'],
      ['#4a8a9a', '#e8e2d0', '#2a4a5a'],
    ],
    like: ['underwater', 'nautical', 'organic', 'retro', 'brass', 'fish'],
    avoid: ['fire', 'desert', 'tactical'],
    groups: [],
    alsoGroups: 'any',
    decoWords: ['fish', 'fin', 'snorkel', 'tentacle', 'shark', 'bubble'],
    keywords: ['underwater', 'ocean', 'sea', 'diver', 'diving', 'aquatic', 'fish', 'water', 'atlantis', 'harpoon'],
    nouns: { crossbow: ['Harpoon Gun', 'Speargun'], rifle: ['Speargun', 'Harpoon Rifle'], bubble_gun: ['Bubble Cannon'] },
  },
  {
    id: 'royal',
    label: 'Royal',
    adj: ['Royal', 'Imperial', 'Golden', 'Regal', 'Crown', 'Majestic', 'Noble', 'Gilded'],
    epithets: ['the Crown', 'the Realm', 'Her Majesty', 'the Throne'],
    palettes: [
      ['#6b2a8a', '#d4af37', '#2a1a3a'],
      ['#f2efe8', '#d4af37', '#1f3a8a'],
      ['#1f3a8a', '#d4af37', '#7a1f1f'],
      ['#7a1f1f', '#d4af37', '#1b1b1b'],
    ],
    like: ['royal', 'ornate', 'fantasy', 'brass', 'fancy', 'magic', 'classic'],
    avoid: ['junk', 'industrial', 'improvised', 'brutal', 'tactical'],
    groups: ['weapon'],
    alsoGroups: 'any',
    decoWords: ['crown', 'gem', 'tassel', 'flag', 'banner', 'bow', 'feather', 'halo'],
    keywords: ['royal', 'king', 'queen', 'gold', 'golden', 'imperial', 'regal', 'noble', 'fancy', 'luxury', 'prince'],
  },
  {
    id: 'spooky',
    label: 'Spooky',
    adj: ['Haunted', 'Cursed', 'Ghoulish', 'Spooky', 'Necro', 'Graveyard', 'Phantom', 'Pumpkin'],
    epithets: ['the Grave', 'All Hallows', 'the Crypt', 'Eternal Night', 'Doom'],
    palettes: [
      ['#2b2b2b', '#ff7a1a', '#6b3fa0'],
      ['#3a3a40', '#7cff4f', '#1b1b1b'],
      ['#e8e2d0', '#2b2b2b', '#7a1f1f'],
      ['#4a2a5a', '#b6ff3b', '#1a1020'],
    ],
    like: ['spooky', 'organic', 'brutal', 'medieval', 'fantasy', 'tribal'],
    avoid: ['toy', 'cute', 'festive', 'clean'],
    groups: [],
    alsoGroups: 'any',
    decoWords: ['skull', 'eyeball', 'tentacle', 'devil', 'candle', 'spikes', 'chain', 'mushroom'],
    keywords: ['spooky', 'halloween', 'haunted', 'ghost', 'cursed', 'zombie', 'undead', 'horror', 'creepy', 'skeleton', 'witch'],
  },
  {
    id: 'arctic',
    label: 'Arctic',
    adj: ['Arctic', 'Frost', 'Glacier', 'Polar', 'Blizzard', 'Cryo', 'Tundra', 'Snowcap'],
    epithets: ['the Frozen North', 'Winter', 'the Blizzard', 'Absolute Zero'],
    palettes: [
      ['#e8f0f8', '#5ab0e0', '#3a4a5a'],
      ['#c8dcf0', '#2a5bd7', '#2b2f38'],
      ['#f2efe8', '#3ad6c8', '#5a6a7a'],
    ],
    like: ['military', 'modern', 'scifi', 'sleek', 'adventure'],
    avoid: ['fire', 'desert', 'jungle'],
    groups: [],
    alsoGroups: 'any',
    decoWords: ['antenna', 'led', 'pompom', 'halo', 'name-tag'],
    keywords: ['arctic', 'ice', 'frost', 'snow', 'frozen', 'cold', 'winter', 'cryo', 'freeze', 'polar'],
    nouns: { flamethrower: ['Freeze Ray', 'Cryo Sprayer'], bubble_gun: ['Snow Blower'] },
    blade: 'palette',
  },
  {
    id: 'tribal',
    label: 'Tribal',
    adj: ['Tribal', 'Totem', 'Jungle', 'Primal', 'Stone-Age', 'Shaman\'s', 'Hunter\'s', 'Bone'],
    epithets: ['the Ancestors', 'the Jungle', 'the Hunt', 'the Spirit Totem'],
    palettes: [
      ['#8a5a32', '#c0392b', '#3a2a1a'],
      ['#a07a4a', '#2f6b3a', '#4a3520'],
      ['#e8e2d0', '#c0392b', '#3a2a1a'],
      ['#6e4424', '#ffb000', '#2b1d12'],
    ],
    like: ['tribal', 'organic', 'wood', 'bone', 'jungle', 'ancient'],
    avoid: ['scifi', 'modern', 'tactical', 'plastic', 'tech'],
    groups: ['weapon'],
    alsoGroups: ['food', 'music', 'garden'],
    decoWords: ['feather', 'skull', 'tassel', 'spikes', 'flower', 'tentacle'],
    keywords: ['tribal', 'jungle', 'primitive', 'caveman', 'stone age', 'shaman', 'totem', 'hunter', 'bone'],
  },
  {
    id: 'cyber',
    label: 'Cyberpunk',
    adj: ['Neon', 'Cyber', 'Glitch', 'Synthwave', 'Chrome', 'Hacker', 'Netrunner', 'Holo'],
    epithets: ['Night City', 'the Grid', 'the Mainframe', 'Ghost Protocol'],
    palettes: [
      ['#15121f', '#00f0ff', '#ff2bd6'],
      ['#1b1d2a', '#ff2bd6', '#24263a'],
      ['#2b2f38', '#b6ff3b', '#15121f'],
      ['#0f141c', '#ffb000', '#00f0ff'],
    ],
    like: ['scifi', 'sleek', 'glow', 'tech', 'modern', 'energy', 'gamer', 'punk'],
    avoid: ['wood', 'medieval', 'ancient', 'tribal', 'steampunk'],
    groups: [],
    alsoGroups: 'any',
    decoWords: ['led', 'antenna', 'sticker-lightning', 'cube', 'lightbulb', 'solar', 'cat-ears'],
    keywords: ['cyberpunk', 'cyber', 'neon', 'hacker', 'synthwave', 'digital', 'glitch', 'chrome', 'retro future', 'vaporwave'],
    blade: 'glow',
  },
  {
    id: 'cozy',
    label: 'Cozy',
    adj: ["Grandma's", 'Cozy', 'Knitted', "Granny's", 'Homely', 'Teatime', 'Doily', 'Crochet'],
    epithets: ['Teatime', 'the Knitting Circle', 'Sunday Lunch', 'Bingo Night'],
    palettes: [
      ['#c79a8a', '#e8d8b0', '#6e4424'],
      ['#8aa0c0', '#f2efe8', '#5a3a22'],
      ['#b05a7a', '#e8e2d0', '#4a3520'],
      ['#9ab08a', '#d4a843', '#5a3a22'],
    ],
    like: ['cute', 'wood', 'retro', 'household', 'silly', 'cozy', 'ornate', 'kitchen'],
    avoid: ['military', 'tactical', 'brutal', 'scifi'],
    groups: ['household', 'kitchen'],
    alsoGroups: ['garden', 'food', 'office', 'music'],
    decoWords: ['bow', 'flower', 'pompom', 'coffee', 'tassel', 'candle', 'cat-ears', 'plushie'],
    keywords: ['grandma', 'granny', 'nana', 'cozy', 'knitted', 'old lady', 'tea', 'homely', 'cottage', 'grandpa'],
  },
];

export const THEME_BY_ID = new Map(THEMES.map((t) => [t.id, t]));

export function themeAllowsGroup(t: Theme, g: ObjGroup): 0 | 1 | 2 {
  if (t.groups.includes(g)) return 2;
  if (t.alsoGroups === 'any' || t.alsoGroups.includes(g)) return 1;
  return 0;
}

export { ALL_GROUPS };
