/** Naming + stat vocabulary for template generation. */
import type { FireMode, MeleeWeight, StatHints, Swing } from './types';

export const CLASS_NOUNS: Record<string, string[]> = {
  pistol: ['Pistol', 'Revolver', 'Sidearm', 'Hand Cannon', 'Blaster'],
  smg: ['SMG', 'Sprayer', 'Machine Pistol', 'Bullet Hose'],
  rifle: ['Rifle', 'Carbine', 'Assault Rifle', 'Repeater'],
  shotgun: ['Shotgun', 'Scattergun', 'Boomstick', 'Blunderbuss'],
  sniper: ['Sniper', 'Longshot', 'Marksman Rifle', 'Sniper Rifle'],
  lmg: ['LMG', 'Machine Gun', 'Minigun', 'Chaingun'],
  rocket_launcher: ['Rocket Launcher', 'Bazooka', 'Launcher'],
  grenade_launcher: ['Grenade Launcher', 'Lobber', 'Mortar'],
  flamethrower: ['Flamethrower', 'Torch', 'Scorcher'],
  bubble_gun: ['Bubble Gun', 'Bubbler', 'Bubble Blaster'],
  blowgun: ['Blowgun', 'Blowpipe', 'Dart Tube'],
  crossbow: ['Crossbow', 'Bolt Thrower', 'Arbalest'],
  melee: ['Blade', 'Weapon'],
  weird: ['Contraption', 'Gizmo', 'Doohickey', 'Thingamajig', 'Launcher', 'Blaster'],
};

/** words that map onto each class in search queries */
export const CLASS_WORDS: Record<string, string[]> = {
  pistol: ['pistol', 'handgun', 'revolver', 'sidearm', 'six-shooter', 'blaster', 'gun'],
  smg: ['smg', 'submachine', 'machine pistol', 'uzi', 'spray'],
  rifle: ['rifle', 'carbine', 'assault', 'ar', 'musket', 'repeater'],
  shotgun: ['shotgun', 'scattergun', 'boomstick', 'blunderbuss', 'spread', 'buckshot'],
  sniper: ['sniper', 'marksman', 'scope', 'scoped', 'railgun', 'longshot', 'long range'],
  lmg: ['lmg', 'machine gun', 'minigun', 'chaingun', 'gatling', 'belt'],
  rocket_launcher: ['rocket', 'bazooka', 'launcher', 'missile', 'rpg', 'cannon'],
  grenade_launcher: ['grenade', 'lobber', 'mortar', 'explosive', 'bomb', 'lob'],
  flamethrower: ['flamethrower', 'flame', 'fire', 'torch', 'burn', 'scorch', 'spray', 'stream', 'hose'],
  bubble_gun: ['bubble', 'bubbles', 'soap', 'foam'],
  blowgun: ['blowgun', 'blowpipe', 'dart', 'darts', 'blow'],
  crossbow: ['crossbow', 'bolt', 'bow', 'arbalest', 'arrow', 'harpoon', 'speargun'],
  melee: ['melee', 'sword', 'axe', 'hammer', 'club', 'bat', 'mace', 'spear', 'blade', 'knife', 'smash', 'swing', 'whack', 'hit', 'bonk'],
  weird: ['weird', 'silly', 'strange', 'contraption', 'gizmo', 'wacky', 'absurd'],
};

export const DEFAULT_FIRE: Record<string, FireMode> = {
  pistol: 'hitscan',
  smg: 'hitscan',
  rifle: 'hitscan',
  shotgun: 'hitscan',
  sniper: 'hitscan',
  lmg: 'hitscan',
  rocket_launcher: 'projectile',
  grenade_launcher: 'arc',
  flamethrower: 'stream',
  bubble_gun: 'projectile',
  blowgun: 'projectile',
  crossbow: 'projectile',
  melee: 'melee',
  weird: 'projectile',
};

export const BASE_STATS: Record<string, StatHints> = {
  pistol: { damage: 'med', fireRate: 'med', range: 'med', spread: 'low', magSize: 'small' },
  smg: { damage: 'low', fireRate: 'fast', range: 'short', spread: 'med', magSize: 'med' },
  rifle: { damage: 'med', fireRate: 'med', range: 'long', spread: 'low', magSize: 'med' },
  shotgun: { damage: 'high', fireRate: 'slow', range: 'short', spread: 'high', magSize: 'small' },
  sniper: { damage: 'high', fireRate: 'slow', range: 'long', spread: 'low', magSize: 'small' },
  lmg: { damage: 'med', fireRate: 'fast', range: 'med', spread: 'med', magSize: 'large' },
  rocket_launcher: { damage: 'high', fireRate: 'slow', range: 'long', projectileSpeed: 'med', magSize: 'small', splash: true },
  grenade_launcher: { damage: 'high', fireRate: 'slow', range: 'med', projectileSpeed: 'slow', magSize: 'small', splash: true },
  flamethrower: { damage: 'low', fireRate: 'fast', range: 'short', spread: 'med', magSize: 'large' },
  bubble_gun: { damage: 'low', fireRate: 'fast', range: 'short', projectileSpeed: 'slow', magSize: 'large' },
  blowgun: { damage: 'med', fireRate: 'slow', range: 'long', projectileSpeed: 'fast', magSize: 'small' },
  crossbow: { damage: 'high', fireRate: 'slow', range: 'long', projectileSpeed: 'fast', magSize: 'small' },
  melee: {},
  weird: { damage: 'med', fireRate: 'med', range: 'med' },
};

export const SWING_VERB: Record<Swing, string> = {
  slash: 'slashes',
  overhead: 'smashes down',
  thrust: 'stabs',
  bash: 'bonks',
  spin: 'whirls',
};

/** melee noun + swing + weight for existing heads / blades (by id substring, first match wins) */
export const HEAD_NOUNS: [RegExp, string, Swing, MeleeWeight][] = [
  [/greataxe/, 'Greataxe', 'overhead', 'heavy'],
  [/axe-bearded/, 'Bearded Axe', 'overhead', 'medium'],
  [/axe-double/, 'Double Axe', 'overhead', 'heavy'],
  [/axe-crescent/, 'Battle Axe', 'overhead', 'heavy'],
  [/hatchet/, 'Hatchet', 'overhead', 'light'],
  [/fireaxe/, 'Fire Axe', 'overhead', 'medium'],
  [/iceaxe/, 'Ice Axe', 'overhead', 'medium'],
  [/axe/, 'Axe', 'overhead', 'medium'],
  [/tomahawk/, 'Tomahawk', 'overhead', 'light'],
  [/halberd/, 'Halberd', 'overhead', 'heavy'],
  [/sledge/, 'Sledgehammer', 'overhead', 'heavy'],
  [/maul/, 'Maul', 'overhead', 'heavy'],
  [/warhammer/, 'Warhammer', 'overhead', 'heavy'],
  [/thunder-hammer/, 'Thunder Hammer', 'overhead', 'heavy'],
  [/squeaky/, 'Squeaky Hammer', 'bash', 'light'],
  [/claw-hammer/, 'Claw Hammer', 'overhead', 'light'],
  [/mallet/, 'Mallet', 'overhead', 'medium'],
  [/gavel/, 'Gavel', 'bash', 'light'],
  [/tenderizer/, 'Meat Tenderizer', 'overhead', 'light'],
  [/mace/, 'Mace', 'overhead', 'medium'],
  [/morningstar/, 'Morning Star', 'spin', 'heavy'],
  [/studded-club|caveman|spiked-club/, 'Club', 'bash', 'medium'],
  [/spear-winged/, 'Boar Spear', 'thrust', 'medium'],
  [/spear/, 'Spear', 'thrust', 'medium'],
  [/bident/, 'Bident', 'thrust', 'medium'],
  [/trident/, 'Trident', 'thrust', 'medium'],
  [/glaive/, 'Glaive', 'slash', 'medium'],
  [/naginata/, 'Naginata', 'slash', 'medium'],
  [/pitchfork/, 'Pitchfork', 'thrust', 'medium'],
  [/war-scythe/, 'War Scythe', 'slash', 'heavy'],
  [/scythe/, 'Scythe', 'slash', 'medium'],
  [/sickle/, 'Sickle', 'slash', 'light'],
  [/frying-pan/, 'Frying Pan', 'bash', 'medium'],
  [/wok/, 'Wok', 'bash', 'medium'],
  [/saucepan/, 'Saucepan', 'bash', 'medium'],
  [/spatula/, 'Spatula', 'bash', 'light'],
  [/ladle/, 'Ladle', 'bash', 'light'],
  [/bat-nails/, 'Nail Bat', 'bash', 'medium'],
  [/bat-barrel/, 'Bat', 'bash', 'medium'],
  [/cricket/, 'Cricket Bat', 'bash', 'medium'],
  [/pickaxe/, 'Pickaxe', 'overhead', 'heavy'],
  [/wrench/, 'Wrench', 'bash', 'medium'],
  [/plunger/, 'Plunger', 'bash', 'light'],
  [/shovel/, 'Shovel', 'bash', 'medium'],
  [/stopsign/, 'Stop Sign', 'bash', 'medium'],
  [/guitar/, 'Guitar', 'overhead', 'medium'],
  [/racket/, 'Racket', 'slash', 'light'],
  [/lollipop/, 'Lollipop', 'bash', 'light'],
  [/toilet-brush/, 'Toilet Brush', 'bash', 'light'],
  [/traffic-sign/, 'Road Sign', 'bash', 'medium'],
];

export const BLADE_NOUNS: [RegExp, string, Swing, MeleeWeight][] = [
  [/longsword-great|zweihander/, 'Greatsword', 'slash', 'heavy'],
  [/longsword/, 'Longsword', 'slash', 'medium'],
  [/broadsword/, 'Broadsword', 'slash', 'heavy'],
  [/wakizashi/, 'Wakizashi', 'slash', 'light'],
  [/nodachi/, 'Nodachi', 'slash', 'heavy'],
  [/katana/, 'Katana', 'slash', 'medium'],
  [/scimitar/, 'Scimitar', 'slash', 'medium'],
  [/sabre/, 'Sabre', 'slash', 'light'],
  [/rapier/, 'Rapier', 'thrust', 'light'],
  [/gladius/, 'Gladius', 'thrust', 'medium'],
  [/leaf/, 'Leaf Blade', 'slash', 'medium'],
  [/flamberge/, 'Flamberge', 'slash', 'heavy'],
  [/kris/, 'Kris', 'thrust', 'light'],
  [/dagger/, 'Dagger', 'thrust', 'light'],
  [/bowie/, 'Bowie Knife', 'slash', 'light'],
  [/tanto/, 'Tanto', 'thrust', 'light'],
  [/cleaver/, 'Cleaver', 'overhead', 'medium'],
  [/machete/, 'Machete', 'slash', 'medium'],
  [/karambit/, 'Karambit', 'slash', 'light'],
  [/falchion/, 'Falchion', 'slash', 'medium'],
  [/khopesh/, 'Khopesh', 'slash', 'medium'],
  [/serrated/, 'Serrated Blade', 'slash', 'medium'],
  [/jagged/, 'Jagged Blade', 'slash', 'heavy'],
  [/chainsaw/, 'Chainsaw Sword', 'slash', 'heavy'],
  [/energy/, 'Laser Sword', 'slash', 'light'],
  [/crystal/, 'Crystal Sword', 'slash', 'medium'],
  [/bone/, 'Bone Blade', 'slash', 'medium'],
  [/wooden/, 'Wooden Sword', 'slash', 'light'],
  [/foam/, 'Foam Sword', 'slash', 'light'],
  [/baguette/, 'Baguette Sword', 'slash', 'light'],
  [/fish/, 'Fish Sword', 'slash', 'light'],
  [/ruler/, 'Ruler Sword', 'slash', 'light'],
  [/cucumber/, 'Cucumber Sword', 'slash', 'light'],
  [/candycane/, 'Candy Cane Sword', 'slash', 'light'],
  [/umbrella/, 'Umbrella Sword', 'thrust', 'light'],
  [/feather/, 'Feather Sword', 'slash', 'light'],
  [/icicle/, 'Icicle Sword', 'thrust', 'light'],
  [/lightning/, 'Lightning Sword', 'slash', 'light'],
  [/keyboard/, 'Keyboard Sword', 'slash', 'medium'],
  [/handsaw/, 'Saw Sword', 'slash', 'medium'],
  [/hooksword/, 'Hook Sword', 'slash', 'medium'],
  [/guitar-neck/, 'Guitar Sword', 'slash', 'medium'],
];

export function lookupNoun(table: [RegExp, string, Swing, MeleeWeight][], id: string): [string, Swing, MeleeWeight] {
  for (const [re, n, s, w] of table) if (re.test(id)) return [n, s, w];
  return ['Weapon', 'slash', 'medium'];
}

/** search synonyms: query word -> extra words to look up */
export const SYNONYMS: Record<string, string[]> = {
  pan: ['frying', 'skillet'],
  skillet: ['frying', 'pan'],
  frypan: ['frying', 'pan'],
  bread: ['baguette', 'loaf'],
  loaf: ['baguette', 'bread'],
  french: ['baguette'],
  brolly: ['umbrella'],
  parasol: ['umbrella'],
  guitar: ['guitar', 'axe'],
  axe: ['axe'],
  gun: ['pistol', 'rifle', 'blaster'],
  blaster: ['pistol', 'blaster'],
  hose: ['hose', 'garden', 'flamethrower'],
  fire: ['flamethrower', 'flame'],
  flame: ['flamethrower', 'flame'],
  flamethrower: ['flame', 'torch'],
  sword: ['sword', 'blade', 'katana', 'longsword'],
  blade: ['sword', 'blade', 'knife'],
  knife: ['knife', 'dagger', 'blade'],
  stick: ['staff', 'club', 'stick'],
  club: ['club', 'bat'],
  hammer: ['hammer', 'mallet', 'sledgehammer'],
  shoots: [],
  shooting: [],
  fires: [],
  launcher: ['launcher', 'rocket', 'grenade'],
  cannon: ['cannon', 'launcher', 'rocket'],
  bomb: ['grenade', 'explosive'],
  water: ['water', 'hose', 'soaker', 'bubble'],
  soap: ['bubble'],
  bubbles: ['bubble'],
  laser: ['laser', 'energy', 'scifi'],
  space: ['scifi', 'space'],
  grandma: ['cozy', 'grandma'],
  granny: ['cozy', 'grandma'],
  nana: ['cozy', 'grandma'],
  grandpa: ['cozy'],
  halloween: ['spooky'],
  christmas: ['holiday'],
  xmas: ['holiday'],
  ninja: ['ninja', 'katana'],
  samurai: ['ninja', 'katana'],
  pirate: ['pirate'],
  cowboy: ['cowboy', 'western'],
  kitchen: ['kitchen', 'cooking'],
  cook: ['kitchen'],
  chef: ['kitchen'],
  mic: ['microphone'],
  phone: ['phone', 'smartphone'],
  cellphone: ['phone', 'smartphone'],
  computer: ['keyboard', 'laptop', 'monitor'],
  tv: ['remote', 'monitor'],
  bat: ['bat', 'baseball'],
  ball: ['ball'],
  duck: ['duck', 'rubber'],
  ducky: ['duck', 'rubber'],
  sausage: ['sausage', 'hot dog'],
  hotdog: ['hot', 'dog', 'sausage'],
  cheese: ['cheese'],
  pizza: ['pizza'],
  icecream: ['ice', 'cream', 'cone'],
  fish: ['fish', 'salmon'],
  chair: ['chair', 'stool'],
  broom: ['broom', 'mop'],
  vacuum: ['vacuum', 'hoover'],
  hoover: ['vacuum'],
  drill: ['drill'],
  chainsaw: ['chainsaw'],
  toilet: ['plunger', 'toilet'],
  plunger: ['plunger'],
  keyboard: ['keyboard'],
  trumpet: ['trumpet', 'horn'],
  horn: ['trumpet', 'horn'],
  sax: ['saxophone'],
  drum: ['drum', 'drumstick'],
  shield: ['shield'],
  spear: ['spear', 'lance'],
  stapler: ['stapler'],
  big: [],
  giant: ['giant'],
  huge: ['giant', 'heavy'],
  tiny: ['compact', 'mini'],
  small: ['compact', 'mini'],
  heavy: ['heavy'],
  fast: ['fast'],
  explosive: ['grenade', 'rocket', 'explosive'],
  ice: ['arctic', 'frost', 'icicle'],
  frost: ['arctic'],
  snow: ['arctic', 'holiday'],
  gold: ['royal', 'golden'],
  golden: ['royal'],
  king: ['royal'],
  queen: ['royal'],
  robot: ['scifi', 'robot'],
  alien: ['alien'],
  zombie: ['spooky'],
  ghost: ['spooky'],
  skeleton: ['spooky', 'skull'],
  candy: ['candycane', 'lollipop', 'sweet'],
  sweets: ['candycane', 'lollipop', 'sweet'],
  rubber: ['rubber', 'duck'],
  music: ['music'],
  rock: ['music', 'guitar'],
};

export const STOPWORDS = new Set(
  'a an the of that which who with and or to from in on at for by is are be as it its my your his her their our this these those shoots shoot shooting fires firing throws throwing launches launching made out like into onto something thing kind sort type weapon weapons really very'.split(
    ' ',
  ),
);
