// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all procedure arg schemas
import * as GenerateWeaponProcedure from "../generate_weapon_procedure";

export type GenerateWeaponArgs = __Infer<typeof GenerateWeaponProcedure.params>;
export type GenerateWeaponResult = __Infer<typeof GenerateWeaponProcedure.returnType>;

