// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddSpawnPointReducer from "../add_spawn_point_reducer";
import ClaimAdminReducer from "../claim_admin_reducer";
import ClearSpawnPointsReducer from "../clear_spawn_points_reducer";
import EquipWeaponReducer from "../equip_weapon_reducer";
import FireReducer from "../fire_reducer";
import RegisterWeaponReducer from "../register_weapon_reducer";
import ReloadReducer from "../reload_reducer";
import RemoveSpawnPointReducer from "../remove_spawn_point_reducer";
import ReportHitReducer from "../report_hit_reducer";
import RespawnReducer from "../respawn_reducer";
import SetApiKeyReducer from "../set_api_key_reducer";
import SetLlmModelReducer from "../set_llm_model_reducer";
import SetNameReducer from "../set_name_reducer";
import UpdateTransformReducer from "../update_transform_reducer";

export type AddSpawnPointParams = __Infer<typeof AddSpawnPointReducer>;
export type ClaimAdminParams = __Infer<typeof ClaimAdminReducer>;
export type ClearSpawnPointsParams = __Infer<typeof ClearSpawnPointsReducer>;
export type EquipWeaponParams = __Infer<typeof EquipWeaponReducer>;
export type FireParams = __Infer<typeof FireReducer>;
export type RegisterWeaponParams = __Infer<typeof RegisterWeaponReducer>;
export type ReloadParams = __Infer<typeof ReloadReducer>;
export type RemoveSpawnPointParams = __Infer<typeof RemoveSpawnPointReducer>;
export type ReportHitParams = __Infer<typeof ReportHitReducer>;
export type RespawnParams = __Infer<typeof RespawnReducer>;
export type SetApiKeyParams = __Infer<typeof SetApiKeyReducer>;
export type SetLlmModelParams = __Infer<typeof SetLlmModelReducer>;
export type SetNameParams = __Infer<typeof SetNameReducer>;
export type UpdateTransformParams = __Infer<typeof UpdateTransformReducer>;

