#!/usr/bin/env node
/**
 * Bake multi-floor spawn points for a processed collision GLB, headlessly (no browser).
 *
 *   node client/scripts/map/bake-spawns.ts <collision.glb> <meta.json> [--spacing 3]
 *
 * Prints a MapSpawn[] JSON array ready to paste into `MAPS[id].spawns`. Uses the same
 * `bakeSpawns()` the client's `?bakeSpawns=1` dev tool calls, so results match.
 */
import { readFileSync } from 'node:fs';
import { writeFile } from 'node:fs/promises';
import { parseArgs } from 'node:util';

import { Document, NodeIO } from '@gltf-transform/core';
import { ALL_EXTENSIONS } from '@gltf-transform/extensions';

import { initPhysics } from '../../src/engine/physics.ts';
import { bakeSpawns } from '../../src/map/bakeSpawns.ts';
import type { GameMap } from '../../src/map/types.ts';

const { values, positionals } = parseArgs({
  args: process.argv.slice(2),
  allowPositionals: true,
  options: { spacing: { type: 'string' }, ts: { type: 'string' }, export: { type: 'string' } },
});
const [glbPath, metaPath] = positionals;
if (!glbPath || !metaPath) {
  console.error('usage: node client/scripts/map/bake-spawns.ts <collision.glb> <meta.json> [--spacing 3] [--ts <file> --export <NAME>]');
  process.exit(1);
}
const spacing = Number(values.spacing ?? 3) || 3;

const io = new NodeIO().registerExtensions(ALL_EXTENSIONS);
const doc: Document = await io.read(glbPath);

const positions: number[] = [];
const indices: number[] = [];
for (const mesh of doc.getRoot().listMeshes()) {
  for (const prim of mesh.listPrimitives()) {
    const pos = prim.getAttribute('POSITION')?.getArray();
    if (!pos) continue;
    const base = positions.length / 3;
    for (let i = 0; i < pos.length; i++) positions.push(pos[i]!);
    const idx = prim.getIndices()?.getArray();
    if (idx) for (let i = 0; i < idx.length; i++) indices.push(idx[i]! + base);
    else for (let i = 0; i < pos.length / 3; i++) indices.push(base + i);
  }
}

const physics = await initPhysics();
const { RAPIER, world } = physics;
world.createCollider(
  RAPIER.ColliderDesc.trimesh(new Float32Array(positions), new Uint32Array(indices), RAPIER.TriMeshFlags.FIX_INTERNAL_EDGES),
);

const meta = JSON.parse(readFileSync(metaPath, 'utf8')) as { bbox: { min: [number, number, number]; max: [number, number, number] } };
const map = { meta: { bbox: meta.bbox } } as unknown as GameMap;
const spawns = bakeSpawns(map, physics, { spacing });

console.error(`[bake-spawns] ${spawns.length} spawns (spacing ${spacing}, ${indices.length / 3} collision tris)`);

if (values.ts) {
  const name = values.export ?? 'SPAWNS';
  const body = spawns
    .map((s) => `  { x: ${s.x}, y: ${s.y}, z: ${s.z}, yaw: ${s.yaw} },`)
    .join('\n');
  const module = `// AUTO-GENERATED by client/scripts/map/bake-spawns.ts — do not edit by hand.\n// Re-run the baker after re-processing the map's collision GLB.\nexport const ${name} = [\n${body}\n] as const;\n`;
  await writeFile(values.ts, module);
  console.error(`[bake-spawns] wrote ${values.ts} (${name})`);
} else {
  console.log(JSON.stringify(spawns, null, 2));
}
