// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  norm: __t.string().primaryKey(),
  designId: __t.u64().name("design_id"),
  firstBy: __t.identity().name("first_by"),
  firstName: __t.string().name("first_name"),
  at: __t.timestamp(),
  uses: __t.u32(),
});
