// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  shooter: __t.identity(),
  target: __t.identity(),
  weaponId: __t.u64().name("weapon_id"),
  damage: __t.f32(),
  killed: __t.bool(),
  dot: __t.bool(),
  x: __t.f32(),
  y: __t.f32(),
  z: __t.f32(),
  knockX: __t.f32().name("knock_x"),
  knockY: __t.f32().name("knock_y"),
  knockZ: __t.f32().name("knock_z"),
  slowPercent: __t.f32().name("slow_percent"),
  headshot: __t.bool(),
  blocked: __t.bool(),
  element: __t.u8(),
});
