// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  owner: __t.identity(),
  name: __t.string(),
  json: __t.string(),
  prompt: __t.string(),
  isPreset: __t.bool().name("is_preset"),
  scale: __t.f32(),
  build: __t.f32(),
  head: __t.f32(),
  maxHp: __t.f32().name("max_hp"),
  speedMult: __t.f32().name("speed_mult"),
  createdAt: __t.timestamp().name("created_at"),
});
