// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  who: __t.identity(),
  pickupId: __t.u32().name("pickup_id"),
  kind: __t.string(),
  amount: __t.f32(),
  x: __t.f32(),
  y: __t.f32(),
  z: __t.f32(),
});
