// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  name: __t.string(),
  online: __t.bool(),
  x: __t.f32(),
  y: __t.f32(),
  z: __t.f32(),
  yaw: __t.f32(),
  pitch: __t.f32(),
  hp: __t.f32(),
  alive: __t.bool(),
  kills: __t.u32(),
  deaths: __t.u32(),
  weaponId: __t.u64().name("weapon_id"),
  ammo: __t.u32(),
  reloading: __t.bool(),
  reloadUntil: __t.timestamp().name("reload_until"),
  lastFireAt: __t.timestamp().name("last_fire_at"),
  respawnAt: __t.timestamp().name("respawn_at"),
  slowPercent: __t.f32().name("slow_percent"),
  slowUntil: __t.timestamp().name("slow_until"),
  dotDps: __t.f32().name("dot_dps"),
  dotUntil: __t.timestamp().name("dot_until"),
  dotSource: __t.identity().name("dot_source"),
  dotWeaponId: __t.u64().name("dot_weapon_id"),
  crouching: __t.bool(),
});
