// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  slot: __t.u16().primaryKey(),
  x: __t.i16(),
  y: __t.i16(),
  z: __t.i16(),
  yaw: __t.u16(),
  pitch: __t.i16(),
  vx: __t.i16(),
  vy: __t.i16(),
  vz: __t.i16(),
  flags: __t.u8(),
  sendT: __t.u32().name("send_t"),
});
