// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Config = __t.object("Config", {
  id: __t.u32(),
  admin: __t.identity(),
  anthropicApiKey: __t.string(),
  llmModel: __t.string(),
});
export type Config = __Infer<typeof Config>;

export const GenerateResult = __t.object("GenerateResult", {
  ok: __t.bool(),
  weaponId: __t.u64(),
  message: __t.string(),
});
export type GenerateResult = __Infer<typeof GenerateResult>;

export const HitEvent = __t.object("HitEvent", {
  shooter: __t.identity(),
  target: __t.identity(),
  weaponId: __t.u64(),
  damage: __t.f32(),
  killed: __t.bool(),
  dot: __t.bool(),
  x: __t.f32(),
  y: __t.f32(),
  z: __t.f32(),
  knockX: __t.f32(),
  knockY: __t.f32(),
  knockZ: __t.f32(),
  slowPercent: __t.f32(),
});
export type HitEvent = __Infer<typeof HitEvent>;

export const Player = __t.object("Player", {
  identity: __t.identity(),
  name: __t.string(),
  online: __t.bool(),
  x: __t.f32(),
  y: __t.f32(),
  z: __t.f32(),
  yaw: __t.f32(),
  pitch: __t.f32(),
  hp: __t.f32(),
  alive: __t.bool(),
  kills: __t.u32(),
  deaths: __t.u32(),
  weaponId: __t.u64(),
  ammo: __t.u32(),
  reloading: __t.bool(),
  reloadUntil: __t.timestamp(),
  lastFireAt: __t.timestamp(),
  respawnAt: __t.timestamp(),
  slowPercent: __t.f32(),
  slowUntil: __t.timestamp(),
  dotDps: __t.f32(),
  dotUntil: __t.timestamp(),
  dotSource: __t.identity(),
  dotWeaponId: __t.u64(),
});
export type Player = __Infer<typeof Player>;

export const Shot = __t.object("Shot", {
  id: __t.u64(),
  shooter: __t.identity(),
  seq: __t.u32(),
  weaponId: __t.u64(),
  firedAt: __t.timestamp(),
  ox: __t.f32(),
  oy: __t.f32(),
  oz: __t.f32(),
  hitTargets: __t.array(__t.identity()),
});
export type Shot = __Infer<typeof Shot>;

export const ShotEvent = __t.object("ShotEvent", {
  shooter: __t.identity(),
  seq: __t.u32(),
  weaponId: __t.u64(),
  ox: __t.f32(),
  oy: __t.f32(),
  oz: __t.f32(),
  dx: __t.f32(),
  dy: __t.f32(),
  dz: __t.f32(),
});
export type ShotEvent = __Infer<typeof ShotEvent>;

export const SpawnPoint = __t.object("SpawnPoint", {
  id: __t.u64(),
  x: __t.f32(),
  y: __t.f32(),
  z: __t.f32(),
  yaw: __t.f32(),
});
export type SpawnPoint = __Infer<typeof SpawnPoint>;

export const TickTimer = __t.object("TickTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type TickTimer = __Infer<typeof TickTimer>;

export const Weapon = __t.object("Weapon", {
  id: __t.u64(),
  ownerIdentity: __t.identity(),
  name: __t.string(),
  weaponClass: __t.string(),
  fireMode: __t.string(),
  json: __t.string(),
  prompt: __t.string(),
  isPreset: __t.bool(),
  createdAt: __t.timestamp(),
});
export type Weapon = __Infer<typeof Weapon>;

