// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Config = __t.object("Config", {
  id: __t.u32(),
  admin: __t.identity(),
  anthropicApiKey: __t.string(),
  llmModel: __t.string(),
});
export type Config = __Infer<typeof Config>;

export const DotTimer = __t.object("DotTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  target: __t.identity(),
});
export type DotTimer = __Infer<typeof DotTimer>;

export const ForgedPrompt = __t.object("ForgedPrompt", {
  norm: __t.string(),
  designId: __t.u64(),
  firstBy: __t.identity(),
  firstName: __t.string(),
  at: __t.timestamp(),
  uses: __t.u32(),
});
export type ForgedPrompt = __Infer<typeof ForgedPrompt>;

export const GenerateResult = __t.object("GenerateResult", {
  ok: __t.bool(),
  weaponId: __t.u64(),
  message: __t.string(),
});
export type GenerateResult = __Infer<typeof GenerateResult>;

export const HitEvent = __t.object("HitEvent", {
  shooter: __t.identity(),
  target: __t.identity(),
  weaponId: __t.u64(),
  damage: __t.f32(),
  killed: __t.bool(),
  dot: __t.bool(),
  x: __t.f32(),
  y: __t.f32(),
  z: __t.f32(),
  knockX: __t.f32(),
  knockY: __t.f32(),
  knockZ: __t.f32(),
  slowPercent: __t.f32(),
  headshot: __t.bool(),
  blocked: __t.bool(),
  element: __t.u8(),
});
export type HitEvent = __Infer<typeof HitEvent>;

export const HitReport = __t.object("HitReport", {
  slot: __t.u32(),
  zone: __t.u8(),
  ix: __t.f32(),
  iy: __t.f32(),
  iz: __t.f32(),
  pellets: __t.u8(),
});
export type HitReport = __Infer<typeof HitReport>;

export const Outfit = __t.object("Outfit", {
  id: __t.u64(),
  owner: __t.identity(),
  name: __t.string(),
  json: __t.string(),
  prompt: __t.string(),
  isPreset: __t.bool(),
  scale: __t.f32(),
  build: __t.f32(),
  head: __t.f32(),
  maxHp: __t.f32(),
  speedMult: __t.f32(),
  createdAt: __t.timestamp(),
});
export type Outfit = __Infer<typeof Outfit>;

export const Pickup = __t.object("Pickup", {
  id: __t.u32(),
  kind: __t.string(),
  x: __t.f32(),
  y: __t.f32(),
  z: __t.f32(),
  available: __t.bool(),
  respawnAt: __t.timestamp(),
  respawnSecs: __t.f32(),
});
export type Pickup = __Infer<typeof Pickup>;

export const PickupEvent = __t.object("PickupEvent", {
  who: __t.identity(),
  pickupId: __t.u32(),
  kind: __t.string(),
  amount: __t.f32(),
  x: __t.f32(),
  y: __t.f32(),
  z: __t.f32(),
});
export type PickupEvent = __Infer<typeof PickupEvent>;

export const PickupTimer = __t.object("PickupTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  pickupId: __t.u32(),
});
export type PickupTimer = __Infer<typeof PickupTimer>;

export const Player = __t.object("Player", {
  identity: __t.identity(),
  name: __t.string(),
  online: __t.bool(),
  x: __t.f32(),
  y: __t.f32(),
  z: __t.f32(),
  yaw: __t.f32(),
  pitch: __t.f32(),
  hp: __t.f32(),
  alive: __t.bool(),
  kills: __t.u32(),
  deaths: __t.u32(),
  weaponId: __t.u64(),
  ammo: __t.u32(),
  reloading: __t.bool(),
  reloadUntil: __t.timestamp(),
  lastFireAt: __t.timestamp(),
  respawnAt: __t.timestamp(),
  slowPercent: __t.f32(),
  slowUntil: __t.timestamp(),
  dotDps: __t.f32(),
  dotUntil: __t.timestamp(),
  dotSource: __t.identity(),
  dotWeaponId: __t.u64(),
  crouching: __t.bool(),
  slot: __t.u32(),
  needsLoadout: __t.bool(),
  dotElement: __t.u8(),
  slowElement: __t.u8(),
  outfitId: __t.u64(),
  maxHp: __t.f32(),
});
export type Player = __Infer<typeof Player>;

export const PlayerCombat = __t.object("PlayerCombat", {
  identity: __t.identity(),
  slot: __t.u32(),
  ammo: __t.u32(),
  reloading: __t.bool(),
  reloadUntil: __t.timestamp(),
  fireCredits: __t.f32(),
  creditsAt: __t.timestamp(),
  poseAt: __t.timestamp(),
  px: __t.f32(),
  py: __t.f32(),
  pz: __t.f32(),
  prevFlags: __t.u8(),
  prevAt: __t.timestamp(),
  dotDps: __t.f32(),
  dotUntil: __t.timestamp(),
  dotSource: __t.identity(),
  dotWeaponId: __t.u64(),
  lastSwingAt: __t.timestamp(),
});
export type PlayerCombat = __Infer<typeof PlayerCombat>;

export const PlayerPose = __t.object("PlayerPose", {
  slot: __t.u32(),
  x: __t.f32(),
  y: __t.f32(),
  z: __t.f32(),
  yaw: __t.f32(),
  pitch: __t.f32(),
  vx: __t.f32(),
  vy: __t.f32(),
  vz: __t.f32(),
  flags: __t.u8(),
  sendT: __t.u32(),
});
export type PlayerPose = __Infer<typeof PlayerPose>;

export const Pose = __t.object("Pose", {
  slot: __t.u16(),
  x: __t.i16(),
  y: __t.i16(),
  z: __t.i16(),
  yaw: __t.u16(),
  pitch: __t.i16(),
  vx: __t.i16(),
  vy: __t.i16(),
  vz: __t.i16(),
  flags: __t.u8(),
  sendT: __t.u32(),
});
export type Pose = __Infer<typeof Pose>;

export const PoseFlushTimer = __t.object("PoseFlushTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type PoseFlushTimer = __Infer<typeof PoseFlushTimer>;

export const PoseState = __t.object("PoseState", {
  identity: __t.identity(),
  slot: __t.u32(),
  alive: __t.bool(),
  x: __t.f32(),
  y: __t.f32(),
  z: __t.f32(),
  yaw: __t.f32(),
  pitch: __t.f32(),
  vx: __t.f32(),
  vy: __t.f32(),
  vz: __t.f32(),
  flags: __t.u8(),
  sendT: __t.u32(),
  poseAt: __t.timestamp(),
  ax: __t.f32(),
  ay: __t.f32(),
  az: __t.f32(),
  aflags: __t.u8(),
  anchorAt: __t.timestamp(),
});
export type PoseState = __Infer<typeof PoseState>;

export const Shot = __t.object("Shot", {
  id: __t.u64(),
  shooter: __t.identity(),
  seq: __t.u32(),
  weaponId: __t.u64(),
  firedAt: __t.timestamp(),
  ox: __t.f32(),
  oy: __t.f32(),
  oz: __t.f32(),
  hitTargets: __t.array(__t.identity()),
});
export type Shot = __Infer<typeof Shot>;

export const ShotEvent = __t.object("ShotEvent", {
  shooter: __t.identity(),
  seq: __t.u32(),
  weaponId: __t.u64(),
  ox: __t.f32(),
  oy: __t.f32(),
  oz: __t.f32(),
  dx: __t.f32(),
  dy: __t.f32(),
  dz: __t.f32(),
  charge: __t.f32(),
  combo: __t.u8(),
});
export type ShotEvent = __Infer<typeof ShotEvent>;

export const SpawnPoint = __t.object("SpawnPoint", {
  id: __t.u64(),
  x: __t.f32(),
  y: __t.f32(),
  z: __t.f32(),
  yaw: __t.f32(),
});
export type SpawnPoint = __Infer<typeof SpawnPoint>;

export const TickTimer = __t.object("TickTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type TickTimer = __Infer<typeof TickTimer>;

export const Weapon = __t.object("Weapon", {
  id: __t.u64(),
  ownerIdentity: __t.identity(),
  name: __t.string(),
  weaponClass: __t.string(),
  fireMode: __t.string(),
  json: __t.string(),
  prompt: __t.string(),
  isPreset: __t.bool(),
  createdAt: __t.timestamp(),
  design: __t.string(),
});
export type Weapon = __Infer<typeof Weapon>;

