// Copies a compact version of ../parts/catalog.json into src/catalog.generated.ts so the
// SpacetimeDB module can bundle it (the module can't read files at runtime).
// If the parts package hasn't produced a catalog yet, an empty catalog is written.
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const src = resolve(here, '../../parts/catalog.json');
const out = resolve(here, '../src/catalog.generated.ts');

let entries = [];
if (existsSync(src)) {
  const raw = JSON.parse(readFileSync(src, 'utf8'));
  const list = Array.isArray(raw) ? raw : Array.isArray(raw.parts) ? raw.parts : Array.isArray(raw.entries) ? raw.entries : [];
  entries = list
    .filter(e => e && typeof e.id === 'string')
    .map(e => ({
      id: e.id,
      category: String(e.category ?? ''),
      classes: Array.isArray(e.classes) ? e.classes.map(String) : [],
      tags: Array.isArray(e.tags) ? e.tags.map(String) : [],
      desc: String(e.desc ?? '').slice(0, 80),
    }));
} else {
  console.warn(`[sync-catalog] ${src} not found; writing empty catalog`);
}

// Example recipes (one or more per class) from parts/src/recipes.ts. Used by generate_weapon's
// no-LLM fallback so random weapons still get a real model. Node >= 22.18 strips TS types natively.
let recipes = [];
const recipesSrc = resolve(here, '../../parts/src/recipes.ts');
if (existsSync(recipesSrc)) {
  try {
    const mod = await import(pathToFileURL(recipesSrc).href);
    const known = new Set(entries.map(e => e.id));
    recipes = (mod.RECIPES ?? [])
      .map(r => ({
        name: String(r.name),
        class: String(r.class),
        parts: (r.parts ?? [])
          .filter(p => known.size === 0 || known.has(p.partId))
          .map(p => {
            const o = { partId: p.partId };
            if (typeof p.color === 'string') o.color = p.color;
            if (typeof p.accent === 'string') o.accent = p.accent;
            if (typeof p.scale === 'number') o.scale = p.scale;
            if (typeof p.socket === 'string') o.socket = p.socket;
            return o;
          }),
      }))
      .filter(r => r.parts.length > 0);
  } catch (e) {
    console.warn(`[sync-catalog] could not load recipes: ${e}`);
  }
}

const body = `// AUTO-GENERATED by scripts/sync-catalog.mjs from parts/catalog.json + parts/src/recipes.ts. Do not edit.
import type { CatalogEntry, WeaponPart } from '@ai-gaem/shared';
export const PART_CATALOG: CatalogEntry[] = ${JSON.stringify(entries)};
export const PART_RECIPES: { name: string; class: string; parts: WeaponPart[] }[] = ${JSON.stringify(recipes)};
`;
let prev = '';
try { prev = readFileSync(out, 'utf8'); } catch {}
if (prev !== body) writeFileSync(out, body);
console.log(`[sync-catalog] ${entries.length} parts, ${recipes.length} recipes`);
